# Generated by Django 3.1.7 on 2021-03-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210320_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agentmodel'),
        ),
    ]
