# Generated by Django 3.2.7 on 2021-10-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_rename_category_categorymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmodel',
            name='Category',
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.categorymodel'),
        ),
    ]
